version: "1.1"
name: Api Check
env:
  host: localhost:3000
tests:
  ping:
    steps:
      - name: GET request
        http:
          url: http://${{env.host}}/ping
          method: GET
          check:
            status: /^20/
  hello:
    testdata:
      file: data.csv
    steps:
      - name: Greeter
        http:
          url: http://${{env.host}}/hello?name=${{ testdata.name }}
          method: GET
          check:
            status: 200
            jsonpath:
              $.hello:
                - eq: itman
