name: Unit Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun
        run: |
          npm install -g bun

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
